kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-webhook-configurations
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - patch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations