---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eap-example
  name: eap-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eap-example
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eap-example
  name: eap-example-ping
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: eap-example
---


apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: eap-example
  name: eap-example
spec:
  to:
    kind: Service
    name: eap-example
---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: eap-example
    application: eap-example
    template: eap71-basic-s2i
    xpaas: 1.4.12
  name: eap-example
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: eap-example
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.agent.vaultproject.io/inject: "true"
        sidecar.agent.vaultproject.io/secret-key: secret/example
        sidecar.agent.vaultproject.io/properties-ext: json
        sidecar.agent.vaultproject.io/vault-role: example
      labels:
        app: eap-example
        application: eap-example
        deploymentConfig: eap-example
      name: eap-example
    spec:
      containers:
        - env:
            - name: JGROUPS_PING_PROTOCOL
              value: openshift.DNS_PING
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: eap-example-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: MQ_CLUSTER_PASSWORD
              value: CQcrHBgO
            - name: MQ_QUEUES
            - name: MQ_TOPICS
            - name: JGROUPS_CLUSTER_PASSWORD
              value: 7YIqtE36
            - name: AUTO_DEPLOY_EXPLODED
              value: 'false'
          image: eap-example
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: eap-example
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8888
              name: ping
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/eap/extensions
              name: jboss-cli
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 75
      volumes:
        - configMap:
            defaultMode: 493
            name: jboss-cli
          name: jboss-cli
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - eap-example
        from:
          kind: ImageStreamTag
          name: 'eap-example:latest'
      type: ImageChange
    - type: ConfigChange
