kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-config
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
data:
  template.ctmpl: |
    {{- with secret "secret/example" -}}
    secret.example.password: {{ .Data.password }}
    {{- end }}
  agent.config: |

    vault {
        ca_path = "/vault/ca/service-ca.crt"
        address = "https://vault.hashicorp.svc.cluster.local:8200"
    }

    pid_file = "/var/run/secrets/vaultproject.io/pid"

    auto_auth {
            method "kubernetes"  {
                    type = "kubernetes"
                    mount_path = "auth/kubernetes"
                    config = {
                            role = "example"
                            jwt = "@/var/run/secrets/kubernetes.io/serviceaccount/token"
                    }
            }

            sink "file" {
                    type = "file"
                    config = {
                            path = "/var/run/secrets/vaultproject.io/token"
                    }
            }

    }

    template {
        source      = "/vault/config/template.ctmpl"
        destination = "/var/run/secrets/vaultproject.io/application.properties"
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-cabundle
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
  name: eap-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
  name: eap-example-ping
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
  name: eap-example
spec:
  to:
    kind: Service
    name: eap-example
---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
  name: eap-example
spec:
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - eap-example
        from:
          kind: ImageStreamTag
          name: 'eap-example:latest'
      type: ImageChange
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app.kubernetes.io/instance: eap-example
    app.kubernetes.io/name: eap-example
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: eap-example
        app.kubernetes.io/name: eap-example
      name: eap-example
    spec:
      initContainers:
      - image: vault:1.3.4
        name: vault-agent-init
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        args:
        - agent
        - -log-level=debug
        - -config=/vault/config/agent.config
        - -exit-after-auth
        env:
        - name: SKIP_SETCAP
          value: 'true'
        volumeMounts:
        - mountPath: /vault/config
          name: vault-config
        - mountPath: /vault/ca
          name: vault-cabundle
        - mountPath: /var/run/secrets/vaultproject.io
          name: vault-agent-volume
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      containers:
        - env:
            - name: JGROUPS_PING_PROTOCOL
              value: openshift.DNS_PING
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: eap-example-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: MQ_CLUSTER_PASSWORD
              value: CQcrHBgO
            - name: MQ_QUEUES
            - name: MQ_TOPICS
            - name: JGROUPS_CLUSTER_PASSWORD
              value: 7YIqtE36
            - name: AUTO_DEPLOY_EXPLODED
              value: 'false'
          image: eap-example
          imagePullPolicy: Always
          name: eap-example
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8888
              name: ping
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/eap/extensions
              name: jboss-cli
            - mountPath: /var/run/secrets/vaultproject.io
              name: vault-agent-volume
        - image: vault:1.3.4
          name: vault-agent
          ports:
          - containerPort: 8200
            name: vaultport
            protocol: TCP
          args:
          - agent
          - -log-level=debug
          - -config=/vault/config/agent.config
          env:
          - name: SKIP_SETCAP
            value: 'true'
          volumeMounts:
          - mountPath: /vault/config
            name: vault-config
          - mountPath: /vault/ca
            name: vault-cabundle
          - mountPath: /var/run/secrets/vaultproject.io
            name: vault-agent-volume
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - sleep 5 && kill -SIGTERM $(pidof vault)
      volumes:
      - name: vault-agent-volume
        emptyDir:
          medium: Memory
      - configMap:
          name: vault-agent-config
        name: vault-config
      - configMap:
          name: vault-agent-cabundle
        name: vault-cabundle
      - configMap:
          defaultMode: 493
          name: jboss-cli
        name: jboss-cli
