apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-injector-binding
  labels:
    app.kubernetes.io/name: vault-injector
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-injector-clusterrole
subjects:
- kind: ServiceAccount
  name: vault-injector
  namespace: hashicorp
