apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: "{{ .Release.Namespace }}-pki-engine"
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  namespace: vault-config-operator
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: controller-manager
  policy: |
    # query existing mounts
    path "/sys/mounts" {
      capabilities = [ "list", "read"]
      allowed_parameters = {
        "type" = ["pki"]
        "*"   = []
      }
    }

    # mount pki secret engines
    path "/sys/mounts/app-pki/{{ .Release.Namespace }}*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    # tune
    path "/sys/mounts/app-pki/{{ .Release.Namespace }}/tune" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    # internal sign pki
    path "pki/intermediate/root/sign-intermediate" {
      capabilities = ["create", "read", "update", "list"]
    }

    # pki 
    path "app-pki/{{ .Release.Namespace }}*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
