---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: team-one
  namespace: team-one
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  authentication:
    path: app-kubernetes/team-one
    role: team-one
  type: pki
  path: app-pki
  config:
    # 1 Year
    maxLeaseTTL: "8760h"
