---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thorntail-example
  name: thorntail-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: thorntail-example
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: thorntail-example
  name: thorntail-example
spec:
  to:
    kind: Service
    name: thorntail-example
---

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: thorntail-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - thorntail-example
        from:
          kind: ImageStreamTag
          name: 'thorntail-example:latest'
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.agent.vaultproject.io/inject: "true"
        sidecar.agent.vaultproject.io/secret-key: secret/example
      labels:
        app: thorntail-example       
    spec:
      containers:
        - args:
            - '-s/var/run/secrets/vaultproject.io/application.yaml'
          command:
            - /opt/run-java/run-java.sh
          name: thorntail-example
          image: "thorntail-example:latest"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3