apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: controller-manager
  labels:
    app.kubernetes.io/instance: vault-config-operator
  annotations:
    kubernetes.io/service-account.name: controller-manager
    argocd.argoproj.io/sync-wave: "-9"