apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: vault-config-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: VAULT_ADDR
      value: https://vault-active.hashicorp-vault.svc:8200
    - name: VAULT_CACERT
      value: /vault-ca/ca.crt
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: controller-manager
          key: token
    volumes:
    - name: vault-ca
      configMap:
        name: int-ca
    volumeMounts:
    - mountPath: /vault-ca
      name: vault-ca