apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
 project: default
 source:
   chart: cert-manager
   repoURL: https://charts.jetstack.io
   targetRevision: 1.9.2
   helm:
    releaseName: cert-manager
    parameters:
    - name: installCRDs
      value:  "true"
 destination:
   server: https://kubernetes.default.svc
   namespace: cert-manager
 syncPolicy:
   automated: {}
   syncOptions:
   - CreateNamespace=true
