apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: deploy/helm/vault-config-operator
    repoURL: 'https://github.com/openlab-red/hashicorp-vault-for-openshift'
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-config-operator
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
