apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
spec:
  destination:
    namespace: hashicorp-vault
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: deploy/helm/vault-install
    #repoURL: 'https://github.com/eye0fra/hashicorp-vault-for-openshift'
    repoURL: 'https://github.com/radudd/hashicorp-vault-for-openshift'
    targetRevision: bugfix/vault-config-operator
  syncPolicy:
    automated: {}
