kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-config
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
data:
  template.ctmpl: |
    {{ with secret "secret/example" }}
    secret:
      example:
        password: {{ .Data.password }}
    {{ end }}
  agent.config: |

    vault {
        ca_path = "/vault/ca/service-ca.crt"
        address = "https://vault.hashicorp.svc.cluster.local:8200"
    }

    pid_file = "/var/run/secrets/vaultproject.io/pid"

    auto_auth {
            method "kubernetes"  {
                    type = "kubernetes"
                    mount_path = "auth/kubernetes"
                    config = {
                            role = "example"
                            jwt = "@/var/run/secrets/kubernetes.io/serviceaccount/token"
                    }
            }

            sink "file" {
                    type = "file"
                    config = {
                            path = "/var/run/secrets/vaultproject.io/token"
                    }
            }

    }

    template {
        source      = "/vault/config/template.ctmpl"
        destination = "/var/run/secrets/vaultproject.io/application.yaml"
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-cabundle
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: python3-example
    app.kubernetes.io/name: python3-example
  name: python3-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python3-example
    app.kubernetes.io/name: python3-example

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: python3-example
    app.kubernetes.io/name: python3-example
  name: python3-example
spec:
  to:
    kind: Service
    name: python3-example

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/instance: python3-example
    app.kubernetes.io/name: python3-example
  name: python3-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - python3-example
        from:
          kind: ImageStreamTag
          name: 'python3-example:latest'
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: python3-example
        app.kubernetes.io/name: python3-example
    spec:
      containers:
      - name: python3-example
        image: python3:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        env:
        - name: PYTHON3_CONFIG_LOCATION
          value: /var/run/secrets/vaultproject.io/application.yaml
        volumeMounts:
        - mountPath: /var/run/secrets/vaultproject.io
          name: vault-agent-volume
      - image: vault:1.3.5
        name: vault-agent
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        args:
        - agent
        - -log-level=debug
        - -config=/vault/config/agent.config
        env:
        - name: SKIP_SETCAP
          value: 'true'
        volumeMounts:
        - mountPath: /vault/config
          name: vault-config
        - mountPath: /vault/ca
          name: vault-cabundle
        - mountPath: /var/run/secrets/vaultproject.io
          name: vault-agent-volume
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5 && kill -SIGTERM $(pidof vault)
      volumes:
      - name: vault-agent-volume
        emptyDir:
          medium: Memory
      - configMap:
          name: vault-agent-config
        name: vault-config
      - configMap:
          name: vault-agent-cabundle
        name: vault-cabundle
