---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python3-example
  name: python3-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python3-example

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: python3-example
  name: python3-example
spec:
  to:
    kind: Service
    name: python3-example

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: python3-example
  name: python3-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - python3-example
        from:
          kind: ImageStreamTag
          name: 'python3-example:latest'
  replicas: 1
  selector:
    app: python3-example
    deploymentconfig: python3-example
  template:
    metadata:
      annotations:
        sidecar.agent.vaultproject.io/inject: "true"
        sidecar.agent.vaultproject.io/secret: secret/example
        sidecar.agent.vaultproject.io/filename: application.yaml
        sidecar.agent.vaultproject.io/role: example
      labels:
        app: python3-example
        deploymentconfig: python3-example
    spec:
      containers:
      - env:
        - name: PYTHON3_CONFIG_ADDITIONAL_LOCATION
          value: /var/run/secrets/vaultproject.io/application.yaml
        image: python3-example:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        name: python3-example
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
