---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: spring-example
    app.kubernetes.io/name: spring-example
  name: spring-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-example

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: spring-example
    app.kubernetes.io/name: spring-example
  name: spring-example
spec:
  to:
    kind: Service
    name: spring-example

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/instance: spring-example
    app.kubernetes.io/name: spring-example
  name: spring-example
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-example
        from:
          kind: ImageStreamTag
          name: 'spring-example:latest'
  replicas: 1
  selector:
    app: spring-example
    deploymentconfig: spring-example
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/ca-key: '/var/run/secrets/kubernetes.io/serviceaccount/ca-bundle/service-ca.crt'
        vault.hashicorp.com/agent-inject-secret-application.yaml: secret/example
        vault.hashicorp.com/agent-inject-template-application.yaml: |
          {{- with secret "secret/example" -}}
          secret:
            example:
              password: {{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/role: example
      labels:
        app: spring-example
        deploymentconfig: spring-example
    spec:
      containers:
      - env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: /vault/secrets/application.yaml
        image: spring-example:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        name: spring-example
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount/ca-bundle
          name: vault-cabundle
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: vault-agent-cabundle
        name: vault-cabundle

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-agent-cabundle
  labels:
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/name: vault-agent
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
