---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  labels:
    operators.coreos.com/vault-config-operator.vault-config-operator: ''
  annotations:
    kubernetes.io/service-account.name: controller-manager
    argocd.argoproj.io/sync-wave: "-12"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: controller-manager
  labels:
    app.kubernetes.io/instance: vault-config-operator
  annotations:
    kubernetes.io/service-account.name: controller-manager
    argocd.argoproj.io/sync-wave: "-11"